version: '2'
services:
  app:
    build: ./app
    ports:
     - "5000:5000"
  #  volumes:
  #   - .:/code
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: password123
